### ISSUE TITLE
How to generate ptest execution report in out side of the directory

### ISSUE THREAD

**Issue by lakshminagandla** [KarlGong/ptest#2]
Hi I have created the project with below structure 

Test
 ---> Smoke 
 ---> Regresssion 

Test Execution Results: 
 ---> Am looking to test execution report over here. 

But am unable to generate the test execution report in desired folder with help of -o or -r attributes as well. 

Note:  I can see test execution report keep on generating inside Test folder.

Could you please help me out here regarding test execution report generation in desired folder.

**Comment by KarlGong** [comment]
If your structure is:
root
 \- Test
 \- \- Smoke
 \- \- Regression

You should cd to root folder, then run `ptest -t Test.Smoke`, the report will be output to root -> test-output.
